import { Inter } from "next/font/google";
import { Background } from "./Components/Background/Background";
import "./globals.css";
import React from "react";


import NavbarComponent from "./Components/Navbar/NavbarComponent";
import OpcitionsBottomComponent from "./Components/OptionsBottom/OpcitionsBottomComponent";
import FooterComponent from "./Components/Footer/FooterComponent";
import NavLateral from "./Components/NavLateral/NavLateral";
import AsideLateral from "./Components/AsideLateral/AsideLateral";



import UserProvider from "@/redux/provider";
import MainComponent from "./Components/MainComponent/MainComponent";
import ButtonState from "./Components/ButtonState/ButtonState";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digital Money App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  const isLogued = false



  return (

      <html lang="en">
        <body className={inter.className}>
         
          <UserProvider> 
         
          <Background />
          <NavbarComponent />

          <ButtonState />
          
          <MainComponent >

          
            <NavLateral />

            {children}

            <AsideLateral />


          </MainComponent>

         

          <OpcitionsBottomComponent />
          <FooterComponent />
         

          </UserProvider>
        </body>
      </html>

  );
}
